CREATE TABLE "sklypai_tableau" (
  "Sklypo_ID" int(11) DEFAULT NULL,
  "Sklypo_adresas" varchar(255) DEFAULT NULL,
  "Plotas" double DEFAULT NULL,
  "Skaitiklis" int(11) DEFAULT NULL,
  "Vardiklis" int(11) DEFAULT NULL,
  "Objekto_ID" int(11) DEFAULT NULL,
  "Moketojo_ID" int(11) DEFAULT NULL,
  "Moketojo_kodas" int(11) DEFAULT NULL,
  "Moketojo_pavadinimas" varchar(255) DEFAULT NULL,
  "Naudojimo_pradzia" varchar(255) DEFAULT NULL,
  "Naudojimo_pabaiga" varchar(255) DEFAULT NULL,
  "Dokumento_data" varchar(255) DEFAULT NULL,
  "lon" double DEFAULT NULL,
  "lat" double DEFAULT NULL,
  "formatted_address" varchar(150) DEFAULT NULL,
  "street_number" varchar(20) DEFAULT NULL,
  "route" varchar(60) DEFAULT NULL,
  "locality" varchar(60) DEFAULT NULL,
  "country" varchar(30) DEFAULT NULL,
  "postal_code" varchar(10) DEFAULT NULL,
  "admin_level_1" varchar(100) DEFAULT NULL,
  "admin_level_2" varchar(100) DEFAULT NULL,
  "admin_level_3" varchar(100) DEFAULT NULL,
  "nuomos_kaina" double DEFAULT NULL,
  "suma" double DEFAULT NULL,
  "nuomos_plotas" double DEFAULT NULL,
  "sumos_pradzia" date DEFAULT NULL,
  "sumos_pabaiga" date DEFAULT NULL,
  KEY "Sklypo_ID" ("Sklypo_ID"),
  KEY "Moketojo_ID" ("Moketojo_ID"),
  KEY "Objekto_ID" ("Objekto_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE "sklypai_skaiciavimai" (
  "ID" int(11) DEFAULT NULL,
  "Objektai_ID" int(11) DEFAULT NULL,
  "Sklypai_ID" int(11) DEFAULT NULL,
  "Kiekis" varchar(255) DEFAULT NULL,
  "Tarifas" varchar(255) DEFAULT NULL,
  "Lengvata" int(11) DEFAULT NULL,
  "Suma" varchar(255) DEFAULT NULL,
  "Suma_be_lengvatos" int(11) DEFAULT NULL,
  "Paslaugos_pradzia" varchar(255) DEFAULT NULL,
  "Paslaugos_pabaiga" varchar(255) DEFAULT NULL,
  "Plotas" varchar(255) DEFAULT NULL,
  "ND_plotas" varchar(255) DEFAULT NULL,
  "TG_kodas" int(11) DEFAULT NULL,
  "VZ_numeris" int(11) DEFAULT NULL,
  "VRV_pozymis" int(11) DEFAULT NULL,
  KEY "Objektai_ID" ("Objektai_ID"),
  KEY "Sklypai_ID" ("Sklypai_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE "sklypai" (
  "Sklypo_ID" int(11) DEFAULT NULL,
  "Sklypo_kodas" varchar(255) DEFAULT NULL,
  "Kadastro_vietoves_kodas" varchar(255) DEFAULT NULL,
  "Kadastro_vietoves_bloko_numeris" varchar(255) DEFAULT NULL,
  "Sklypo_nr_bloke" int(11) DEFAULT NULL,
  "Anuliavimo_data" varchar(255) DEFAULT NULL,
  "Pagal_pastata" int(11) DEFAULT NULL,
  "Sklypo_adresas" varchar(255) DEFAULT NULL,
  "Laikotarpis" varchar(255) DEFAULT NULL,
  "Bazine_kaina" varchar(255) DEFAULT NULL,
  "Plotas" double DEFAULT NULL,
  "Paskirties_kodas" int(11) DEFAULT NULL,
  "Paskirtis" varchar(255) DEFAULT NULL,
  "Charakteristikos_kodas" varchar(255) DEFAULT NULL,
  "Charakteristika" varchar(255) DEFAULT NULL,
  "Turto_grupes_kodas" varchar(255) DEFAULT NULL,
  "Turto_grupe" varchar(255) DEFAULT NULL,
  "Verciu_zona" varchar(255) DEFAULT NULL,
  "Skaitiklis" int(11) DEFAULT NULL,
  "Vardiklis" int(11) DEFAULT NULL,
  "Neapmokestinamas_dydis" varchar(255) DEFAULT NULL,
  "Objekto_ID" int(11) DEFAULT NULL,
  "Moketojo_ID" int(11) DEFAULT NULL,
  "Moketojo_kodas" int(11) DEFAULT NULL,
  "Moketojo_pavadinimas" varchar(255) DEFAULT NULL,
  "Naudojimo_pradzia" varchar(255) DEFAULT NULL,
  "Naudojimo_pabaiga" varchar(255) DEFAULT NULL,
  "Taikyti_VRV" int(11) DEFAULT NULL,
  "VRV_visa" varchar(255) DEFAULT NULL,
  "VRV_dalies" varchar(255) DEFAULT NULL,
  "Dokumento_data" varchar(255) DEFAULT NULL,
  "Dokumento_nr" varchar(255) DEFAULT NULL,
  "Dokumento_tipas" varchar(255) DEFAULT NULL,
  "Koregavimo_data" varchar(255) DEFAULT NULL,
  "lon" double DEFAULT NULL,
  "lat" double DEFAULT NULL,
  "formatted_address" varchar(150) DEFAULT NULL,
  "street_number" varchar(20) DEFAULT NULL,
  "route" varchar(60) DEFAULT NULL,
  "locality" varchar(60) DEFAULT NULL,
  "country" varchar(30) DEFAULT NULL,
  "postal_code" varchar(10) DEFAULT NULL,
  "admin_level_1" varchar(100) DEFAULT NULL,
  "admin_level_2" varchar(100) DEFAULT NULL,
  "admin_level_3" varchar(100) DEFAULT NULL,
  KEY "Sklypo_ID" ("Sklypo_ID"),
  KEY "Moketojo_ID" ("Moketojo_ID"),
  KEY "Objekto_ID" ("Objekto_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8;